[package]
name = "ramiel"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.28"
log = "0.4"
env_logger = "0.11.0"
clap = { version = "4.5.32", features = ["derive"] }

[profile.release]
debug = true
strip = false
