use super::registers::*;

pub enum Instruction {
    ADD(ArithmeticTarget),
    ADDHL(),
    ADC(ArithmeticTarget),
    SUB(ArithmeticTarget),
    SBC(ArithmeticTarget),
    AND(ArithmeticTarget),
    OR(ArithmeticTarget),
    XOR(ArithmeticTarget),
    CP(ArithmeticTarget),
    INC(ArithmeticTarget),
    DEC(ArithmeticTarget),
    CCF(),
    SCF(),
    RRA(),
    RLA(),
    RRCA(),
    RRLA(),
    CPL(),
    BIT(ArithmeticTarget),
    RESET(ArithmeticTarget),
    SET(ArithmeticTarget),
    SRL(ArithmeticTarget),
    RR(ArithmeticTarget),
    RL(ArithmeticTarget),
    RRC(ArithmeticTarget),
    RLC(ArithmeticTarget),
    SRA(ArithmeticTarget),
    SLA(ArithmeticTarget),
    SWAP(ArithmeticTarget),
    NOP(),
    STOP(),
    LD(ArithmeticTarget),
}

impl Instruction{
    pub fn from_byte(byte: u8) -> Option<Instruction> { 
        match byte {
            0x00 => { Some(Instruction::NOP()) },
            0x01 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x02 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x03 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x04 => { Some(Instruction::INC(ArithmeticTarget::B)) },
            0x05 => { Some(Instruction::DEC(ArithmeticTarget::B)) },
            0x06 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x07 => { Some(Instruction::RLC(ArithmeticTarget::A)) },
            0x08 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x09 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x0A => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x0B => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x0C => { Some(Instruction::INC(ArithmeticTarget::C)) },
            0x0D => { Some(Instruction::DEC(ArithmeticTarget::C)) },
            0x0E => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x0F => { Some(Instruction::RRC(ArithmeticTarget::A)) },

            0x10 => { Some(Instruction::STOP()) },
            0x11 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x12 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x13 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x14 => { Some(Instruction::INC(ArithmeticTarget::D)) },
            0x15 => { Some(Instruction::DEC(ArithmeticTarget::D)) },
            0x16 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x17 => { Some(Instruction::RL(ArithmeticTarget::A)) },
            0x18 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x19 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x1A => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x1B => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x1C => { Some(Instruction::INC(ArithmeticTarget::E)) },
            0x1D => { Some(Instruction::DEC(ArithmeticTarget::E)) },
            0x1E => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x1F => { Some(Instruction::RR(ArithmeticTarget::A)) },

            0x20 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x21 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x22 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x23 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x24 => { Some(Instruction::INC(ArithmeticTarget::H)) },
            0x25 => { Some(Instruction::DEC(ArithmeticTarget::H)) },
            0x26 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x27 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x28 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x29 => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x2A => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x2B => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x2C => { Some(Instruction::INC(ArithmeticTarget::L)) },
            0x2D => { Some(Instruction::DEC(ArithmeticTarget::L)) },
            0x2E => { unimplemented!("Instruction not implemented yet: {:#X}", byte) },
            0x2F => { Some(Instruction::CPL()) },
            _ => panic!("Instruction not implemented yet: {:#X}", byte),
        }
     }
}